services:
  - type: web
    name: news-curation-app
    env: python
    plan: free
    buildCommand: |
      cd client && npm install && npm run build &&
      cd ../backend && pip install -r requirements.txt
    startCommand: cd backend && python main.py
    healthCheckPath: /health
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: GROQ_API_KEY
        sync: false
      - key: PORT
        value: 5000
    autoDeploy: false