services:
  - type: web
    name: lets-stay-updated
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false             
      - key: GROQ_API_KEY
        sync: false 
      - key: LLM_PROVIDER
        value: groq
      - key: PORT
        value: 5000
    autoDeploy: false
